### PR TITLE
Add Cake Contrib logo variations

### PR DESCRIPTION
**Pull request by augustoproiete**
Add the 5 Cake Contrib logo variations:

<div align="center">
<table>
  <tr>
    <td align="center">Addin</td>
    <td align="center">Module</td>
    <td align="center">Recipe</td>
    <td align="center">Frosting Recipe</td>
    <td align="center">Community</td>
  </tr>
  <tr>
    <td align="center">Cake Contrib Addin logo</td>
    <td align="center">Cake Contrib Module logo</td>
    <td align="center">Cake Contrib Recipe logo</td>
    <td align="center">Cake Contrib Frosting Recipe logo</td>
    <td align="center">Cake Contrib Community logo</td>
  </tr>
</table>
</div>

---

ps: This PR also adds the version of the logos without text in case it's useful in the future (see files ending with `--no-text.png`)

### CODE REVIEW

**Review by devlead — APPROVED** [review]
LGTM 👍

**Review by nils-a — APPROVED** [review]
🎉👍

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@augustoproiete thanks for getting these added!

**Pull request merged**
